### ISSUE TITLE
关于Freecamera的问题

### ISSUE THREAD

**Issue by AImouse** [DreamRealmCraft/tweakeroo-forge#1]
不知道是不是我的设置问题，Freecamera功能似乎并没有实现

**Comment by Forgot-Dream** [comment]
请给出复现过程和游戏运行环境（客户端版本、Forge版本、Mod列表等）。最好是以截图或者日志的形式。

**Comment by AImouse** [comment]
> 请给出复现过程和游戏运行环境（客户端版本、Forge版本、Mod列表等）。最好是以截图或者日志的形式。

抱歉，是我个人的设置问题，给大佬添麻烦了
