### ISSUE TITLE
Game Crashes after adding performant mod

### ISSUE THREAD

**Issue by HusK-918** [DreamRealmCraft/tweakeroo-forge#6]
Title. After I add performant it just crashes and im no professional in reading crash logs but i can see it mentions tweakeroo as the error

Crash Log: https://paste.atlauncher.com/view/483b5207-4edb-4b45-b781-2acf0fa48c69

Edit: The game doesn't crash when I remove tweakeroo

**Comment by Forgot-Dream** [comment]
`[04/08/2023 04:02:48 AM] [pool-4-thread-1/FATAL] Mixin apply failed mixins.tweakeroo.json:MixinLivingEntity -> net.minecraft.world.entity.LivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/entity/LivingEntity::removeOwnPotionEffects with priority 990 cannot inject into net/minecraft/world/entity/LivingEntity::m_21217_()V merged by com.performant.coremod.mixin.entity.LivingEntityMixin with priority 998 [PREINJECT Applicator Phase -> mixins.tweakeroo.json:MixinLivingEntity -> Prepare Injections ->  -> handler$zij000$removeOwnPotionEffects(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]`

You can simply understand that performant and tweakeroo have modified the same code in MC to cause a conflict, and I'm not going to fix that. I can only guarantee that most of the features of the ported version will work, compatibility issues are not among the issues I am willing to fix.
